// <auto-generated />
namespace TESTVPS_EntityFramwork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FIX_Ngaoerror : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FIX_Ngaoerror));
        
        string IMigrationMetadata.Id
        {
            get { return "202002291625156_FIX_Ngaoerror"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
